FROM registry.access.redhat.com/ubi9 AS ubi-micro-build

ADD target/unpacked/ /tmp/keycloak/

RUN mv /tmp/keycloak/keycloak-* /opt/keycloak
RUN mv /opt/keycloak/data/import /opt/keycloak && mkdir -p /opt/keycloak/data && mv /opt/keycloak/import /opt/keycloak/data/import
RUN chmod -R g+rwX /opt/keycloak

ADD container/ubi-null.sh /tmp/
RUN bash /tmp/ubi-null.sh java-17-openjdk-headless glibc-langpack-en findutils

FROM registry.access.redhat.com/ubi9-micro as keycloak-base
ENV LANG en_US.UTF-8

# Flag for determining app is running in container
ENV KC_RUN_IN_CONTAINER true

# Add the AI engine properties as ENV vars and the default provider here
#--------------------
# ENV KC_SPI_AI_ENGINE_PROVIDER <YOUR_CUSTOM_PROVIDER_ID>
# ENV OPEN_AI_API_KEY           <YOUR_API_KEY>
# ENV OPEN_AI_API_ORGANIZATION  <YOUR_ORGANIZATION_ID>
# ENV OPEN_AI_API_PROJECT       <YOUR_PROJECT_ID>
#--------------------

COPY --from=ubi-micro-build /tmp/null/rootfs/ /
COPY --from=ubi-micro-build --chown=1000:0 /opt/keycloak /opt/keycloak

RUN echo "keycloak:x:0:root" >> /etc/group && \
    echo "keycloak:x:1000:0:keycloak user:/opt/keycloak:/sbin/nologin" >> /etc/passwd

USER 1000

RUN /opt/keycloak/bin/kc.sh import --dir=/opt/keycloak/data/import
RUN /opt/keycloak/bin/kc.sh build

ENV KEYCLOAK_ADMIN admin
ENV KEYCLOAK_ADMIN_PASSWORD admin

EXPOSE 8080
EXPOSE 8443
EXPOSE 9000

ENTRYPOINT [ "/opt/keycloak/bin/kc.sh" ]