name: Build Keycloak Adaptive Authentication extension

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build extension
      run: ./mvnw clean install -DskipTests

  test:
    name: Simple tests
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - name: Test execute 'build' command
      run: ./mvnw exec:exec@build