name: Build Keycloak Adaptive Authentication extension

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build extension
      run: ./mvnw clean install -DskipTests -Pbuild-distribution

    - name: Test execute 'build' command
      run: ./mvnw exec:exec@build